<a href="https://colab.research.google.com/github/pm390/RecSys_AfterLesson_Notebooks/blob/master/Beginning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 1 october 2020

Let's start with imports needed for the lesson arguments


In [2]:
from numpy import *
import numpy as np
import scipy 
from scipy.sparse import *

only for readability of random floats

In [3]:
 import decimal
 decimal.getcontext().rounding = decimal.ROUND_DOWN

Let's create a URM as a sparse matrix 


In [11]:
M = lil_matrix((5,5))
rng = np.random.default_rng()
M[0,0]=1*round(decimal.Decimal(rng.random()),2)
M[1,1]=1*round(decimal.Decimal(rng.random()),2)
M[0,4]=1*round(decimal.Decimal(rng.random()),2)
M[1,3]=1*round(decimal.Decimal(rng.random()),2)
M[2,2]=1*round(decimal.Decimal(rng.random()),2)
M[3,2]=1*round(decimal.Decimal(rng.random()),2)
M[4,4]=1*round(decimal.Decimal(rng.random()),2)
print("dense Version : \n",M.todense())
print("sparse : \n",M)
Mu=csr_matrix(M)
Mi=csc_matrix(M)
Mo=coo_matrix(M)
print("sparse row:-----------------","\nindices : ",Mu.indices,"\nindptr : ",Mu.indptr,"\ndata : ",Mu.data)
print("sparse column:--------------","\nindices : ",Mi.indices,"\nindptr : ",Mi.indptr,"\ndata : ",Mi.data)
print("sparse coordinate:----------","\nrow :",Mo.row,"\ncolumn : ",Mo.col,"\ndata : ",Mo.data)
print("shapes")
print("Mu : ",Mu.shape)
print("Mi : ",Mi.shape)
print("Mo : ",Mo.shape)

dense Version : 
 [[0.87 0.   0.   0.   0.02]
 [0.   0.11 0.   0.3  0.  ]
 [0.   0.   0.81 0.   0.  ]
 [0.   0.   0.52 0.   0.  ]
 [0.   0.   0.   0.   0.72]]
sparse : 
   (0, 0)	0.87
  (0, 4)	0.02
  (1, 1)	0.11
  (1, 3)	0.3
  (2, 2)	0.81
  (3, 2)	0.52
  (4, 4)	0.72
sparse row:----------------- 
indices :  [0 4 1 3 2 2 4] 
indptr :  [0 2 4 5 6 7] 
data :  [0.87 0.02 0.11 0.3  0.81 0.52 0.72]
sparse column:-------------- 
indices :  [0 1 2 3 1 0 4] 
indptr :  [0 1 2 4 5 7] 
data :  [0.87 0.11 0.81 0.52 0.3  0.02 0.72]
sparse coordinate:---------- 
row : [0 0 1 1 2 3 4] 
column :  [0 4 1 3 2 2 4] 
data :  [0.87 0.02 0.11 0.3  0.81 0.52 0.72]
shapes
Mu :  (5, 5)
Mi :  (5, 5)
Mo :  (5, 5)


The columns are the items. The rows are the users.

---
Start with getting for each user his ratings



In [5]:
for i in range(Mu.shape[1]):
  row_start = Mu.indptr[i]
  row_end= Mu.indptr[i+1]
  print("user",i,"ratings   : " , Mu.data[row_start:row_end])
  print("user",i,"items     : " , Mu.indices[row_start:row_end])


user 0 ratings   :  [0.83 0.42]
user 0 items     :  [0 4]
user 1 ratings   :  [0.26 0.98]
user 1 items     :  [1 3]
user 2 ratings   :  [0.76]
user 2 items     :  [2]
user 3 ratings   :  [0.39]
user 3 items     :  [2]
user 4 ratings   :  [0.06]
user 4 items     :  [4]


Let's get for each item its ratings

In [6]:
for i in range(Mi.shape[1]):
  column_start = Mi.indptr[i]
  column_end= Mi.indptr[i+1]
  print("item",i,"ratings   : " , Mi.data[column_start:column_end])
  print("item",i,"users     : " , Mi.indices[column_start:column_end])


item 0 ratings   :  [0.83]
item 0 users     :  [0]
item 1 ratings   :  [0.26]
item 1 users     :  [1]
item 2 ratings   :  [0.76 0.39]
item 2 users     :  [2 3]
item 3 ratings   :  [0.98]
item 3 users     :  [1]
item 4 ratings   :  [0.42 0.06]
item 4 users     :  [0 4]


# Let's dive into Non personalized recommendations



Top popular 

In [13]:
Mi.sum(0)


matrix([[0.87, 0.11, 1.33, 0.3 , 0.74]])